{{ 
    config(
        materialized='table'
        )
}}

WITH TRANSFORMED_EVENTS AS (
    SELECT 
        EVENT_USERNAME AS USERNAME,
        MAX(CASE WHEN EVENT_NAME = 'RegisterEvent' THEN EVENT_DATETIME ELSE NULL END) AS REGISTERED_AT,
        MIN(CASE WHEN EVENT_NAME = 'LoginEvent' THEN EVENT_DATETIME ELSE NULL END) AS FIRST_LOGGED_IN_AT,
        MAX(CASE WHEN EVENT_NAME = 'LoginEvent' THEN EVENT_DATETIME ELSE NULL END) AS LAST_LOGGED_IN_AT,
        COUNT(DISTINCT CASE WHEN EVENT_NAME = 'LoginEvent' THEN EVENT_ID ELSE NULL END) AS LOGIN_COUNT,
        MIN(CASE WHEN EVENT_NAME = 'PurchaseEvent' THEN EVENT_DATETIME ELSE NULL END) AS FIRST_PURCHASED_AT,
        MAX(CASE WHEN EVENT_NAME = 'PurchaseEvent' THEN EVENT_DATETIME ELSE NULL END) AS LAST_PURCHASED_AT,
        COUNT(DISTINCT CASE WHEN EVENT_NAME = 'PurchaseEvent' THEN EVENT_ID ELSE NULL END) AS PURCHASE_COUNT
    FROM 
        {{ source('dwh', 'events') }}
    GROUP BY
        EVENT_USERNAME
)

, FINAL AS (
    SELECT *, NOW() as EVENT_TRANSFORMED_TIMESTAMP
        
    FROM TRANSFORMED_EVENTS
)

SELECT * FROM FINAL